services:
  postgres:
    image: postgres:17
    container_name: postgres_dev
    environment:
      POSTGRES_DB: bookshelf
      POSTGRES_USER: bookshelf
      POSTGRES_PASSWORD: bookshelf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookshelf -d bookshelf"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Your Go app service (uncomment when ready)
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: golang_app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: devuser
  #     DB_PASSWORD: devpassword
  #     DB_NAME: devdb
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./:/app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
